# Generated by Django 3.0.6 on 2020-05-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
