# Generated by Django 3.0.6 on 2020-05-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0005_auto_20200526_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
